version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27020:27017
  app:
    build:
      .
    environment:
      - NODE_ENV=staging
      - MONGODB_URI=mongodb://mongo/ss-products
    ports:
      - 3000:3000
